<<<<<<< HEAD
spring.application.name=business-service

server.port=8081

# ===============================
# Database Configuration
# ===============================
=======
server.port=8081

>>>>>>> 539bd96fd1185a2797a6384936b888cd0cc1336a
spring.datasource.url=jdbc:mysql://localhost:3306/p06_eduhub
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

<<<<<<< HEAD
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT Configuration
# IMPORTANT:
# Secret key MUST be same as Auth Service
# ===============================
jwt.secret=eduhubSecretKeyForJwtAuthentication123456789012345
jwt.expiration=3600000

# ===============================
# Logging (Optional)
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
=======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=eduhubSecretKeyForJwtAuthentication123456789012345
jwt.expiration=3600000

# Fix Jackson serialization issue for Hibernate Lazy Proxies
spring.jackson.serialization.fail-on-empty-beans=false
>>>>>>> 539bd96fd1185a2797a6384936b888cd0cc1336a
